"""empty message

Revision ID: 03ccdf67f9eb
Revises: 753839c44909
Create Date: 2022-04-11 17:44:14.751515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ccdf67f9eb'
down_revision = '753839c44909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
