"""empty message

Revision ID: 282e50432cbb
Revises: 7643a0fdf144
Create Date: 2022-04-18 18:10:11.587025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282e50432cbb'
down_revision = '7643a0fdf144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_img_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_user_img_key', 'user', ['user_img'])
    # ### end Alembic commands ###
