"""empty message

Revision ID: 64765fdccaa8
Revises: d162dd48f1da
Create Date: 2022-03-28 18:24:24.470394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64765fdccaa8'
down_revision = 'd162dd48f1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
