"""empty message

Revision ID: bb6de97508ad
Revises: 2807edd385a2
Create Date: 2022-03-22 23:05:25.103379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6de97508ad'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('apellido', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('apellido_seg', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('img', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'img')
    op.drop_column('user', 'apellido_seg')
    op.drop_column('user', 'apellido')
    op.drop_table('role')
    # ### end Alembic commands ###
