"""empty message

Revision ID: c7b68db21fc0
Revises: c89875e8dae8
Create Date: 2022-03-23 22:36:36.625461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b68db21fc0'
down_revision = 'c89875e8dae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
