"""empty message

Revision ID: c89875e8dae8
Revises: bb6de97508ad
Create Date: 2022-03-23 18:41:01.411220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89875e8dae8'
down_revision = 'bb6de97508ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'apellido')
    op.drop_column('user', 'apellido_seg')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('apellido_seg', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('apellido', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
