"""empty message

Revision ID: d05ca9a2d563
Revises: c7b68db21fc0
Create Date: 2022-03-24 17:41:46.280886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05ca9a2d563'
down_revision = 'c7b68db21fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img', sa.String(length=150), nullable=True))
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'img')
    # ### end Alembic commands ###
